# Generated by Django 6.0.3 on 2026-03-13 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created at Village'), ('QUALITY_CHECKED', 'Quality Verified'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received by Processor'), ('REJECTED', 'Rejected')], default='CREATED', max_length=20)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, help_text='Moisture % at harvest', max_digits=5, null=True)),
                ('foreign_matter_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Foreign matter %', max_digits=5, null=True)),
                ('quality_grade', models.CharField(blank=True, default='', help_text='Final assigned grade: A, B, C', max_length=10)),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_village', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_traces', to='marketplace.order')),
                ('produce_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_traces', to='marketplace.producelog')),
            ],
        ),
        migrations.CreateModel(
            name='InputProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SEEDS', 'Seeds'), ('FERTILIZER', 'Fertilizer'), ('PESTICIDE', 'Pesticide'), ('EQUIPMENT', 'Farm Equipment')], default='SEEDS', max_length=20)),
                ('brand', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('stock_available', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_products', to='marketplace.processorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InputOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed'), ('CONFIRMED', 'Confirmed by Supplier'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=20)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_input_orders', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_orders', to='marketplace.farmerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.inputproduct')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_type', models.CharField(choices=[('HARVEST', 'At Harvest (Agent)'), ('AGGREGATION', 'At Aggregation Center'), ('TRANSIT', 'During Transit'), ('RECEIVING', 'At Processor Dock')], max_length=20)),
                ('inspector_name', models.CharField(max_length=150)),
                ('passed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='marketplace.batchtrace')),
            ],
        ),
    ]
